language: elixir
elixir:
  - 1.0.5
  - 1.1.0-rc.0
otp_release:
  - 17.5
  - 18.0
sudo: false
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cd test_app
  - cat config/database.config >> config/test.exs
script:
  - mix deps.get
  - mix espec --silent
notifications:
  recipients:
    - anton.mishchuk@gmail.com
