language: elixir
elixir:
  - 1.3.4
  - 1.4.5
  - 1.5.0
otp_release:
  - 18.3
  - 19.2
matrix:
  include:
    - elixir: 1.4.5
      otp_release: 20.0
    - elixir: 1.5.0
      otp_release: 20.0
sudo: false
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cd rumbrella/apps/rumbl
  - cat config/database.config >> config/test.exs
  - cat config/test.secret.exs >> config/dev.secret.exs
  - cd ../../..
script:
  - mix deps.get
  - mix espec
  - cd rumbrella
  - mix deps.get
  - mix test
  - mix espec
notifications:
  recipients:
    - anton.mishchuk@gmail.com
