language: elixir
elixir:
  - 1.0.5
  - 1.1.0-rc.0
otp_release:
  - 17.5
  - 18.0
sudo: false
script:
  - cd test_app && mix test
  - cd test_app && mix espec --silent
notifications:
  recipients:
    - anton.mishchuk@gmail.com
